# ============================================================
#  SECTION 5 — CHROME: header, pause, confirm, export, dashboard
# ============================================================

header() {
    clear
    printf '\033[1;34m'
    echo "  ┌─────────────────────────────────────────────────────────┐"
    printf "  │  ▲  Z-MENU  v%-6s  ·  LOCAL SOVEREIGN                │\n" "$ZMENU_VERSION"
    echo "  └─────────────────────────────────────────────────────────┘"
    printf '\033[0m\n'
}

pause() {
    [[ "$ZMENU_HEADLESS" -eq 1 ]] && { echo "  [headless: done]"; return; }
    echo ""; read -rp "  $(printf '%b' "${DIM}[Enter] back${NC}") " _
}

confirm() {
    local prompt="$1"
    read -rp "  ${prompt} (y/N): " _c
    [[ "$_c" =~ ^[Yy]$ ]]
}

submenu_footer() {
    echo ""
    echo -e "  ${DIM}─────────────────────────────────────────${NC}"
    echo -e "  ${DIM}[Enter]=back    [r]=refresh    [q]=quit zmenu${NC}"
}

# ── Session logging ────────────────────────────────────────
_session_log() {
    local action="$1"
    local detail="${2:-}"
    local result="${3:-}"
    mkdir -p "$ZMENU_HISTORY_DIR"
    # Use Python to generate valid JSON — prevents injection if detail/result contain quotes/newlines
    _SL_T="$(date -Iseconds)" \
    _SL_A="$action" \
    _SL_D="$detail" \
    _SL_R="$result" \
    python3 -c '
import json,os
record={"t":os.environ.get("_SL_T",""),"action":os.environ.get("_SL_A",""),"detail":os.environ.get("_SL_D",""),"result":os.environ.get("_SL_R","")}
print(json.dumps(record))
' >> "$ZMENU_SESSION_LOG"
    chmod 600 "$ZMENU_SESSION_LOG" 2>/dev/null || true
}

# ── Export function — available from any screen ────────────
# Captures current terminal output context into a markdown file
export_report() {
    local section="${1:-General}"
    local extra_content="${2:-}"
    {
        echo "# Z-Menu Report"
        echo "> Section: ${section}"
        echo "> Generated: $(date '+%Y-%m-%d %H:%M:%S')"
        echo "> Version: ${ZMENU_VERSION}"
        echo ""

        echo "## System Overview"
        echo "- CPU: ${D_CPU_MODEL} (${D_CPU_CORES} threads, governor: ${D_CPU_GOVERNOR})"
        echo "- RAM: ${D_MEM_USED_MB}/${D_MEM_TOTAL_MB} MB used (${D_MEM_FREE_MB} MB free)"
        echo "- Swap: ${D_SWAP_USED_MB}/${D_SWAP_TOTAL_MB} MB"
        local disk_info; disk_info=$(df -h / | awk 'NR==2{printf "%s used / %s (%s free)",$3,$2,$4}') || true
        echo "- Disk: ${disk_info}"
        echo "- Load: $(awk '{print $1,$2,$3}' /proc/loadavg)"
        echo ""

        echo "## AI Stack"
        if [[ "$D_ZENNY_RUNNING" == true ]]; then
            echo "- Zenny-Core: RUNNING (PID ${D_ZENNY_PID:-?})"
            echo "- Models: ${D_ZENNY_MODELS[*]:-none}"
        else
            echo "- Zenny-Core: STOPPED"
        fi
        if [[ "$D_GATEWAY_RUNNING" == true ]]; then
            echo "- LLM-Gateway: RUNNING at ${D_GATEWAY_URL} (v${D_GATEWAY_VER})"
            local _gi
            for _gi in "${!D_GATEWAY_SLOTS_VAR[@]}"; do
                printf "  - %-22s  %-8s  %s  %s MB  inflight:%s\n" \
                    "${D_GATEWAY_SLOTS_VAR[$_gi]}" \
                    "${D_GATEWAY_SLOTS_STATE[$_gi]}" \
                    "${D_GATEWAY_SLOTS_MODEL[$_gi]}" \
                    "${D_GATEWAY_SLOTS_RSS[$_gi]}" \
                    "${D_GATEWAY_SLOTS_INFLIGHT[$_gi]}"
            done
        else
            echo "- LLM-Gateway: STOPPED"
        fi
        if [[ "$D_OLLAMA_RUNNING" == true ]]; then
            echo "- Ollama: RUNNING at ${D_OLLAMA_URL}"
            echo "- Active model: ${D_OLLAMA_ACTIVE_MODEL:-none}"
            echo "- Available: ${D_OLLAMA_MODELS[*]:-none}"
            echo "- Context window: ${ZMENU_AI_CONTEXT_LENGTH}"
        else
            echo "- Ollama: STOPPED"
        fi
        echo ""

        echo "## GPU"
        echo "- Driver: ${D_GPU_DRIVER:-none}"
        echo "- GFX: ${D_GPU_GFX:-unknown}"
        [[ -n "$D_GPU_TEMP" ]] && echo "- Temp: ${D_GPU_TEMP}°C"
        [[ -n "$D_GPU_USE" ]] && echo "- Utilisation: ${D_GPU_USE}%"
        echo ""

        echo "## Docker"
        if [[ "$D_DOCKER_RUNNING" == true ]]; then
            echo "- Status: RUNNING (${#D_CONTAINERS[@]} containers)"
            for c in "${D_CONTAINERS[@]}"; do echo "  - ${c}"; done
        else
            echo "- Status: STOPPED"
        fi
        echo ""

        if [[ -n "$extra_content" ]]; then
            echo "## ${section} Details"
            echo "$extra_content"
            echo ""
        fi

        echo "---"
        echo "*Report generated by zmenu v${ZMENU_VERSION}*"
    } > "$ZMENU_REPORT_FILE"
    echo -e "  ${OK}  Report saved to ${BOLD}${ZMENU_REPORT_FILE}${NC}"
}

# ── Dashboard status display ──────────────────────────────
# This is the home screen — shows everything at a glance
dashboard() {
    # ── Refresh live metrics ──
    _disc_memory
    _disc_lemonade || true
    _disc_hermes || true
    _disc_process_groups || true
    _history_load_trend 5 || true

    # Load sparkline data
    local _spark_gpu="" _spark_ram="" _spark_load=""
    local _pts="${ZMENU_SPARKLINE_POINTS:-30}"
    _sparkline_read "gpu_temp" "$_pts" || true
    [[ -n "${D_SPARKLINE_VALS:-}" ]] && _spark_gpu=$(_sparkline_render "$D_SPARKLINE_VALS" "$D_SPARKLINE_MAX")
    _sparkline_read "ram_used_mb" "$_pts" || true
    [[ -n "${D_SPARKLINE_VALS:-}" ]] && _spark_ram=$(_sparkline_render "$D_SPARKLINE_VALS" "$D_SPARKLINE_MAX")
    _sparkline_read "load1" "$_pts" || true
    [[ -n "${D_SPARKLINE_VALS:-}" ]] && _spark_load=$(_sparkline_render "$D_SPARKLINE_VALS" "$D_SPARKLINE_MAX")

    # ── AI Engine (computed early, rendered last) ─────────
    local _zenny _zenny_info
    local _zenny_instances; _zenny_instances=$(pgrep -x "$ZENNY_PROCESS" 2>/dev/null | wc -l) || true
    if [[ "$D_ZENNY_RUNNING" == true ]]; then
        if [[ "$_zenny_instances" -gt 1 ]]; then
            _zenny=$WARN
            _zenny_info="${#D_ZENNY_MODELS[@]} model(s)  pid:${D_ZENNY_PID:-?}  ${_zenny_instances} instances"
        else
            _zenny=$OK
            _zenny_info="${#D_ZENNY_MODELS[@]} model(s)  pid:${D_ZENNY_PID:-?}"
        fi
    else
        _zenny=$IDLE; _zenny_info="stopped"
    fi

    local _olla _olla_info
    if [[ "$D_OLLAMA_RUNNING" == true ]]; then
        _olla=$OK; _olla_info="running at ${D_OLLAMA_URL}"
    else
        _olla=$IDLE; _olla_info="stopped"
    fi

    local _lms
    $D_LMS_RUNNING && _lms=$OK || _lms=$IDLE

    # ── Memory Pool ───────────────────────────────────────
    # Real breakdown: used = apps+cache; available = what apps can actually use
    local mem_pct=0 avail_pct=0
    [[ "$D_MEM_TOTAL_MB" -gt 0 ]] && mem_pct=$((D_MEM_USED_MB * 100 / D_MEM_TOTAL_MB))
    [[ "$D_MEM_TOTAL_MB" -gt 0 ]] && avail_pct=$((D_MEM_AVAIL_MB * 100 / D_MEM_TOTAL_MB))
    local _mem
    if [[ $avail_pct -gt 30 ]]; then _mem=$OK
    elif [[ $avail_pct -gt 10 ]]; then _mem=$WARN
    else _mem=$FAIL; fi

    # Memory consumers (top 5 by RSS)
    local mem_consumers
    mem_consumers=$(ps aux --sort=-rss 2>/dev/null \
        | awk 'NR>1 && NR<=6{printf "      %-18s %5.0f MB\n", $11, $6/1024}' || true)

    # Zenny-Core loaded models / tok/s
    local zenny_loaded=""
    if [[ "$D_ZENNY_RUNNING" == true ]]; then
        local stats_resp
        stats_resp=$(_zenny_send '{"cmd":"stats"}' 2>/dev/null || echo "")
        if [[ -n "$stats_resp" ]]; then
            zenny_loaded=$(echo "$stats_resp" | python3 -c "
import json,sys
try:
    d=json.loads(sys.stdin.read())
    for m in d.get('models',[]):
        name=m.get('name','?')
        toks=m.get('tok_s',0)
        print(f'      Zenny: {name}  {toks:.0f} tok/s')
except: pass
" 2>/dev/null || true)
        fi
    fi

    # Swap
    local _swap
    if [[ "$D_SWAP_USED_MB" -gt 100 ]]; then _swap=$WARN
    elif [[ "$D_SWAP_USED_MB" -gt 0 ]]; then _swap=$OK
    else _swap=$IDLE; fi

    # ── GPU ───────────────────────────────────────────────
    local _gpu _gpu_info
    local _gpu_trend="" _gpu_use_trend=""
    [[ -n "${D_HIST_GPU_TEMP:-}" ]] && _gpu_trend=$(_history_trend_str "${D_GPU_TEMP:-0}" "$D_HIST_GPU_TEMP" "°C")
    [[ -n "${D_HIST_GPU_USE:-}" ]]  && _gpu_use_trend=$(_history_trend_str "${D_GPU_USE:-0}" "$D_HIST_GPU_USE" "%")
    case "$D_GPU_DRIVER" in
        rocm)         _gpu=$OK;   _gpu_info="${D_GPU_GFX}  ${D_GPU_TEMP:-?}°C ${_gpu_trend}  ${D_GPU_USE:-?}% ${_gpu_use_trend}" ;;
        nvidia)       _gpu=$OK;   _gpu_info="${D_GPU_GFX}  ${D_GPU_TEMP:-?}°C ${_gpu_trend}  ${D_GPU_USE:-?}% ${_gpu_use_trend}" ;;
        amdgpu-sysfs) _gpu=$WARN; _gpu_info="sysfs only  ${D_GPU_TEMP:-?}°C ${_gpu_trend}  ${DIM}(rocm-smi not in PATH)${NC}" ;;
        *)            _gpu=$IDLE; _gpu_info="not detected" ;;
    esac

    # ── NPU ───────────────────────────────────────────────
    # NPU is always-on hardware — $OK when driver+device present (ready),
    # $IDLE only if driver missing (not usable)
    local _npu _npu_info
    if [[ -n "$D_NPU_DRIVER" && -n "$D_NPU_DEVICE" && "$D_NPU_DEVICE" != "no-device" ]]; then
        _npu=$OK; _npu_info="${D_NPU_DRIVER}  ${D_NPU_DEVICE}  ${DIM}(XDNA — available)${NC}"
    elif [[ -n "$D_NPU_DRIVER" ]]; then
        _npu=$WARN; _npu_info="${D_NPU_DRIVER} loaded, no device found"
    else
        _npu=$IDLE; _npu_info="driver not loaded"
    fi

    # ── Docker ────────────────────────────────────────────
    local _dock _dock_info
    if [[ "$D_DOCKER_RUNNING" == true ]]; then
        _dock=$OK; _dock_info="${#D_CONTAINERS[@]} container(s)"
    else
        _dock=$FAIL; _dock_info="stopped"
    fi

    # ── Disk ──────────────────────────────────────────────
    local disk_pct; disk_pct=$(df / | awk 'NR==2{gsub(/%/,"",$5); print $5}') || true
    local _disk
    if [[ "$disk_pct" -lt 70 ]]; then _disk=$OK
    elif [[ "$disk_pct" -lt 85 ]]; then _disk=$WARN
    else _disk=$FAIL; fi

    # ── Thermals ──────────────────────────────────────────
    local cpu_temp=""
    if command -v sensors >/dev/null 2>&1; then
        cpu_temp=$(sensors 2>/dev/null | awk '/Tctl|Tdie/{gsub(/[+°C]/,"",$2); print $2; exit}' || echo "")
    fi
    [[ -z "$cpu_temp" ]] && cpu_temp=$(cat /sys/class/thermal/thermal_zone*/temp 2>/dev/null | head -1 | awk '{printf "%.0f", $1/1000}' || echo "?")
    local _therm
    local therm_val="${cpu_temp:-0}"
    # Handle decimal temps (e.g. 79.2) by stripping decimal part
    therm_val="${therm_val%%.*}"
    if [[ "$therm_val" =~ ^[0-9]+$ ]]; then
        if [[ $therm_val -lt 70 ]]; then _therm=$OK
        elif [[ $therm_val -lt 85 ]]; then _therm=$WARN
        else _therm=$FAIL; fi
    else
        _therm=$IDLE
    fi

    # ── Load ──────────────────────────────────────────────
    local load1; load1=$(awk '{print $1}' /proc/loadavg)
    local _load
    local load_int=${load1%.*}
    local core_count=${D_CPU_CORES:-4}
    if [[ $load_int -lt $core_count ]]; then _load=$OK
    elif [[ $load_int -lt $((core_count * 2)) ]]; then _load=$WARN
    else _load=$FAIL; fi

    # ── RENDER ────────────────────────────────────────────
    echo -e "  ${BOLD}${BBLU}┄ DASHBOARD ────────────────────────────────────────────${NC}"
    echo ""

    # Recently used — top 3 recent menu selections from session log
    local _recent
    _recent=$(tail -100 "$ZMENU_SESSION_LOG" 2>/dev/null | grep '"action":"menu_select"' | \
        python3 -c "import sys,json; items=[json.loads(l).get('detail','') for l in sys.stdin]; uniq=[]; [uniq.append(x) for x in items if x not in uniq]; print(', '.join(uniq[:3]))" 2>/dev/null || true)
    if [[ -n "$_recent" ]]; then
        echo -e "  ${DIM}Recent:${NC}  $_recent"
        echo ""
    fi

    # Hardware — primary for a discovery system
    echo -e "  ${BOLD}Hardware${NC}"
    echo -e "    GPU       ${_gpu}  ${_gpu_info}"
    [[ -n "$_spark_gpu" ]] && echo -e "    ${DIM}      ${_spark_gpu}${NC}"
    echo -e "    NPU       ${_npu}  ${_npu_info}"
    echo -e "    Thermals  ${_therm}  CPU: ${cpu_temp:-?}°C  GPU: ${D_GPU_TEMP:-?}°C"
    local _load_trend=""
    [[ -n "${D_HIST_LOAD1:-}" ]] && _load_trend=$(_history_trend_str "$load1" "$D_HIST_LOAD1" "")
    echo -e "    Load      ${_load}  $(awk '{printf "%s %s %s",$1,$2,$3}' /proc/loadavg)  ${_load_trend} ${DIM}(${D_CPU_CORES} threads)${NC}"
    [[ -n "$_spark_load" ]] && echo -e "    ${DIM}      ${_spark_load}${NC}"
    if [[ "$_load" == "$FAIL" ]]; then
        echo -e "    ${BRED}→ CRITICAL: System overloaded! Use KILL MODE (option 1)${NC}"
    elif [[ "$_load" == "$WARN" ]]; then
        echo -e "    ${BYEL}→ Load high. KILL MODE (option 1) can help.${NC}"
    fi
    echo ""

    # Memory Pool
    local _ram_trend=""
    [[ -n "${D_HIST_RAM_USED:-}" ]] && _ram_trend=$(_history_trend_str "${D_MEM_USED_MB:-0}" "$D_HIST_RAM_USED" "MB")
    echo -e "  ${BOLD}Memory Pool${NC}    ${_mem}  ${D_MEM_USED_MB}/${D_MEM_TOTAL_MB} MB used ${_ram_trend} ·  ${D_MEM_AVAIL_MB} MB available"
    [[ -n "$_spark_ram" ]] && echo -e "    ${DIM}      ${_spark_ram}${NC}"
    echo -e "    ${_swap}  Swap: ${D_SWAP_USED_MB}/${D_SWAP_TOTAL_MB} MB"
    if [[ -n "$mem_consumers" ]]; then
        echo -e "    ${DIM}Top consumers:${NC}"
        echo -e "$mem_consumers"
    fi
    if [[ "$_mem" == "$FAIL" ]]; then
        echo -e "    ${BRED}→ CRITICAL: Memory low! Use KILL MODE (option 1)${NC}"
    elif [[ "$_mem" == "$WARN" ]]; then
        echo -e "    ${BYEL}→ Memory stressed. KILL MODE (option 1) can help.${NC}"
    fi
    echo ""

    # Running Backends & Apps
    local _apps_any=false
    if [[ "$D_LEMONADE_RUNNING" == true || "$D_HERMES_RUNNING" == true || \
          "$D_DOCKER_RUNNING" == true || ${#D_PROCESS_GROUPS[@]} -gt 0 ]]; then
        echo -e "  ${BOLD}Running Backends & Apps${NC}"
        _apps_any=true
    fi
    if [[ "$D_LEMONADE_RUNNING" == true || ${#D_LEMONADE_BACKENDS[@]} -gt 0 ]]; then
        if [[ "$D_LEMONADE_RUNNING" == true ]]; then
            echo -e "    Lemonade  ${OK}  port ${D_LEMONADE_PORT:-?}  pid ${D_LEMONADE_PID:-?}"
        else
            echo -e "    Lemonade  ${IDLE}  not running"
        fi
        local _b
        for _b in "${D_LEMONADE_BACKENDS[@]}"; do
            local _b_name _b_type _b_port _b_pid _b_ram
            IFS='|' read -r _b_name _b_type _b_port _b_pid _b_ram <<< "$_b"
            echo -e "      ${_b_name}  ${OK}  port ${_b_port:-—}  pid ${_b_pid}  ${_b_ram} MB"
        done
    fi
    if [[ "$D_HERMES_RUNNING" == true ]]; then
        echo -e "    Hermes"
        [[ -n "$D_HERMES_DESKTOP_PID" ]] && echo -e "      Desktop  ${OK}  pid ${D_HERMES_DESKTOP_PID}"
        [[ -n "$D_HERMES_CLI_PID" ]]     && echo -e "      CLI      ${OK}  pid ${D_HERMES_CLI_PID}"
        [[ -n "$D_HERMES_GATEWAY_PID" ]] && echo -e "      Gateway  ${OK}  pid ${D_HERMES_GATEWAY_PID}"
    fi
    if [[ "$D_DOCKER_RUNNING" == true ]]; then
        echo -e "    Docker    ${OK}  ${#D_CONTAINERS[@]} container(s)"
        local _c
        for _c in "${D_CONTAINERS[@]}"; do
            local _cname _cstatus
            _cname="${_c%%:*}"
            _cstatus="${_c#*:}"
            echo -e "      ${_cname}  ${DIM}${_cstatus}${NC}"
        done
    fi
    # Top CPU consumers by group
    local cpu_groups
    cpu_groups=$(ps aux --sort=-%cpu 2>/dev/null | awk '
        NR>1 {
            cmd=$11; cpu=$3
            if (cmd ~ /lemond|llama-server|sd-server|whisper-server|kokoro-server|koko/) grp="Lemonade"
            else if (cmd ~ /Hermes|hermes_cli|hermes.*gateway/) grp="Hermes"
            else if (cmd ~ /docker|containerd/) grp="Docker"
            else if (cmd ~ /zed|zeditor/) grp="Zed"
            else if (cmd ~ /zenny-core/) grp="Zenny"
            else if (cmd ~ /ollama/) grp="Ollama"
            else if (cmd ~ /python.*gateway|llm-gateway/) grp="LLM-Gateway"
            else grp=cmd
            gcpu[grp]+=cpu
        }
        END {
            for (g in gcpu) printf "%.1f %s\n", gcpu[g], g
        }
    ' | sort -rn | head -5 | awk '{printf "      %-14s %5.1f %%\n", $2":", $1}' || true)
    if [[ -n "$cpu_groups" ]]; then
        echo -e "    ${DIM}Top CPU consumers:${NC}"
        echo -e "$cpu_groups"
    fi
    if $_apps_any; then
        echo ""
    fi

    # Kworker storm alert
    if [[ "$D_KWORKER_STORM" == true ]]; then
        _kworker_dashboard_alert
    fi

    # Services
    echo -e "  ${BOLD}Services${NC}"
    echo -e "    Docker    ${_dock}  ${_dock_info}"
    echo -e "    Disk      ${_disk}  ${disk_pct}% used"
    echo ""

    # AI Engine — last, collapsible (only if any backend is running)
    local _ai_any=false
    if [[ "$D_ZENNY_RUNNING" == true || "$D_OLLAMA_RUNNING" == true || \
          "$D_LMS_RUNNING" == true || "$D_CLAUDE_SESSION" == true || \
          "$D_GATEWAY_RUNNING" == true ]] || \
       pgrep -x "$OPENCODE_PROCESS" >/dev/null 2>&1; then
        echo -e "  ${BOLD}AI Engine${NC}"
        _ai_any=true
    fi
    if [[ "$D_ZENNY_RUNNING" == true ]]; then
        echo -e "    Zenny-Core  ${_zenny}  ${_zenny_info}"
    fi
    if [[ "$D_CLAUDE_SESSION" == true ]]; then
        echo -e "    Claude Code ${OK}  session active  v${D_CLAUDE_VER}"
    fi
    if pgrep -x "$OPENCODE_PROCESS" >/dev/null 2>&1; then
        echo -e "    OpenCode    ${OK}  RUNNING  v$( "$(_opencode_cmd)" --version 2>/dev/null || echo '?' )"
    fi
    if [[ "$D_OLLAMA_RUNNING" == true ]]; then
        echo -e "    Ollama      ${OK}  running at ${D_OLLAMA_URL}"
    fi
    if [[ "$D_LMS_RUNNING" == true ]]; then
        echo -e "    LM Studio   ${OK}  ${D_LMS_URL}"
    fi
    if [[ "$D_GATEWAY_RUNNING" == true ]]; then
        echo -e "    LLM-Gateway ${OK}  v${D_GATEWAY_VER}  ${D_GATEWAY_URL}"
        local _slot_color _slot_state
        for i in "${!D_GATEWAY_SLOTS_VAR[@]}"; do
            _slot_state="${D_GATEWAY_SLOTS_STATE[$i]}"
            _slot_color=$IDLE
            [[ "$_slot_state" == "Active" ]] && _slot_color=$OK
            [[ "$_slot_state" == "Error" ]]  && _slot_color=$FAIL
            echo -e "      ${D_GATEWAY_SLOTS_VAR[$i]}  ${_slot_color}  ${D_GATEWAY_SLOTS_MODEL[$i]}  ${D_GATEWAY_SLOTS_RSS[$i]} MB  ${_slot_state}"
        done
    fi
    if $_ai_any; then
        echo ""
    fi

    # Wiki — one-liner status only
    local wiki_ts="" wiki_changes=0
    [[ -f "${ZMENU_WIKI_DIR}/hardware.md" ]] && \
        wiki_ts=$(head -1 "${ZMENU_WIKI_DIR}/hardware.md" | sed 's/# Hardware — //')
    [[ -f "${ZMENU_WIKI_DIR}/changes.md" ]] && \
        wiki_changes=$(grep -c '^## ' "${ZMENU_WIKI_DIR}/changes.md" 2>/dev/null || echo 0)
    if [[ -n "$wiki_ts" ]]; then
        echo -e "  ${DIM}Wiki: refreshed ${wiki_ts}  ·  ${wiki_changes} changes  ·  4=System Scan for full inventory${NC}"
    fi

    echo ""
    echo -e "  ${DIM}$(date '+%a %d %b %Y  %H:%M:%S')  ·  ●=active  ○=stopped  ●=warning  ●=error${NC}"
    echo ""
}

